version: '3.9'

networks:
  demo-network:
    driver: bridge

services:
  db:
    image: postgres:13-alpine
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - demo-network
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - .volumes/postgresql/postgresql:/var/lib/postgresql
      - .volumes/postgresql/postgresql_data:/var/lib/postgresql/data
